version: '3'

services:
  file-storage:
    image: minio/minio:latest
    restart: unless-stopped
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - '2898:9000'
      - '2899:9001'
    environment:
      MINIO_ROOT_USER: 'minio-root'
      MINIO_ROOT_PASSWORD: 'minio-root'

  doc-watcher:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - '.env.production'
    ports:
      - '2893:2893'
    volumes:
      - './doc-watcher/indexer/:/app/indexer'
