[logger]
Level="INFO"
FilePath="./logs/app.log"
EnableFileLog=false

[watcher]
Address="0.0.0.0:2893"
WatchedDirectories="./indexer/watcher"

[ocr]
Address="http://localhost:8004"
Mode="raw"
Timeout=300

[searcher]
Address="http://localhost:2892"
Timeout=300

[tokenizer]
Address="http://localhost:8001"
Mode="none"
ChunkSize=800
ChunkOverlap=100
ReturnChunks=false
ChunkBySelf=false
Timeout=30

[storage]
DriverName="postgres"
User="metabase"
Password="metabase"
Address="localhost"
Port=5432
DbName="documents"
EnableSSL="disable"
AddressLLM="http://localhost:8081"

[office]
Address="http://localhost:8087/example"

[minio]
Address="0.0.0.0:2894"
MinioEndpoint="localhost:9000"
BucketName="indexer"
MinioRootUser="LPlcgMtidFuByIBEuJJ8"
MinioRootPassword="pwEPAAaX6bPh99qXzSazxSP6DUm1gHPgY1js2kV0"
Address="0.0.0.0:2893"
BucketName="common-folder"
MinioRootUser="0TOUjvrbLX1Hf0CQmGaB"
MinioRootPassword="K6hgghVAsem3m1UcdfYLHkIDOoTXo1IOdvkcja7F"
MinioUseSSL=false
