[server]
Address="0.0.0.0:2893"
LoggerLevel="INFO"

[ocr]
Address="localhost:8004"
EnableSSL=false
Timeout=300

[searcher]
Address="localhost:2892"
EnableSSL=false

[embeddings]
Address="localhost:8001"
EnableSSL=false
ChunkSize=800
ChunkOverlap=100
ReturnChunks=false
ChunkBySelf=false

[watcher]
Address="localhost:9000"
Username="minio-root"
Password="minio-root"
EnableSSL=false
WatchedDirectories="common-folder"
CacheExpire=10
CacheCleanInterval=30
