definitions:
  httpserv.AttachDirectoryForm:
    properties:
      bucket_name:
        example: test-folder
        type: string
    type: object
  httpserv.BadRequestForm:
    properties:
      message:
        example: Bad Request message
        type: string
      status:
        example: 400
        type: integer
    type: object
  httpserv.FetchDocumentsList:
    properties:
      file_names:
        example:
        - test-file.docx
        items:
          type: string
        type: array
    type: object
  httpserv.ResponseForm:
    properties:
      message:
        example: Done
        type: string
      status:
        example: 200
        type: integer
    type: object
  httpserv.ServerErrorForm:
    properties:
      message:
        example: Server Error message
        type: string
      status:
        example: 503
        type: integer
    type: object
  watcher.ProcessingDocuments:
    properties:
      done:
        items:
          type: string
        type: array
      processing:
        items:
          type: string
        type: array
      unrecognized:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /watcher/{bucket}/detach:
    delete:
      consumes:
      - application/json
      description: Attach new directory to watcher
      operationId: folders-detach
      parameters:
      - description: Folder ids
        in: path
        name: bucket
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserv.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserv.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserv.ServerErrorForm'
      summary: Attach new directory to watcher
      tags:
      - watcher
  /watcher/attach:
    put:
      consumes:
      - application/json
      description: Attach new directory to watcher
      operationId: folders-attach
      parameters:
      - description: File entity
        in: body
        name: jsonQuery
        required: true
        schema:
          $ref: '#/definitions/httpserv.AttachDirectoryForm'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserv.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserv.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserv.ServerErrorForm'
      summary: Attach new directory to watcher
      tags:
      - watcher
  /watcher/processing/clean:
    post:
      consumes:
      - application/json
      description: Clean processing documents
      operationId: clean-documents
      parameters:
      - description: File names to clean processing status
        in: body
        name: jsonQuery
        required: true
        schema:
          $ref: '#/definitions/httpserv.FetchDocumentsList'
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserv.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserv.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserv.ServerErrorForm'
      summary: Clean processing documents
      tags:
      - watcher
  /watcher/processing/fetch:
    post:
      consumes:
      - application/json
      description: Load processing/unrecognized/done documents by names list
      operationId: fetch-documents
      parameters:
      - description: File names to fetch processing status
        in: body
        name: jsonQuery
        required: true
        schema:
          $ref: '#/definitions/httpserv.FetchDocumentsList'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/watcher.ProcessingDocuments'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserv.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserv.ServerErrorForm'
      summary: Fetch processing documents
      tags:
      - watcher
  /watcher/run:
    get:
      description: Run all watchers
      operationId: watcher-run
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserv.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserv.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserv.ServerErrorForm'
      summary: Run all watchers
      tags:
      - watcher
  /watcher/stop:
    get:
      description: Stop all watchers
      operationId: watcher-stop
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/httpserv.ResponseForm'
        "400":
          description: Bad Request message
          schema:
            $ref: '#/definitions/httpserv.BadRequestForm'
        "503":
          description: Server does not available
          schema:
            $ref: '#/definitions/httpserv.ServerErrorForm'
      summary: Stop all watchers
      tags:
      - watcher
swagger: "2.0"
